#!/usr/bin/env node
/**
 * Generates Bridges/Today.md — a context dashboard from the filesystem.
 * No Dataview. No network.
 *
 *   OBSIDIAN_VAULT=/path/to/vault node scripts/generate-today.mjs
 *
 * Time zone: OBSIDIAN_TIME_ZONE (default Asia/Bangkok).
 */
import fs from "fs/promises";
import path from "path";

const VAULT = process.env.OBSIDIAN_VAULT || path.join(process.env.HOME || "", "Documents/SecondBrain");
const TIME_ZONE = (() => {
  const requested = (process.env.OBSIDIAN_TIME_ZONE || "Asia/Bangkok").trim() || "Asia/Bangkok";
  try {
    new Intl.DateTimeFormat("en-CA", { timeZone: requested }).format(new Date());
    return requested;
  } catch {
    return "Asia/Bangkok";
  }
})();

function todayInZone() {
  return new Date().toLocaleString("sv-SE", { timeZone: TIME_ZONE }).slice(0, 10);
}

function weekLabel(dateStr) {
  const d = new Date(`${dateStr}T12:00:00Z`);
  const year = d.getUTCFullYear();
  const jan4 = new Date(Date.UTC(year, 0, 4));
  const startOfWeek1 = new Date(jan4);
  startOfWeek1.setUTCDate(jan4.getUTCDate() - ((jan4.getUTCDay() + 6) % 7));
  const week = Math.floor((d - startOfWeek1) / (7 * 24 * 3600 * 1000)) + 1;
  return `${year}-W${String(week).padStart(2, "0")}`;
}

function previousDay(dateStr) {
  const d = new Date(`${dateStr}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() - 1);
  return d.toISOString().slice(0, 10);
}

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fm = {};
  for (const line of match[1].split("\n")) {
    const [key, ...rest] = line.split(":");
    if (key && rest.length) fm[key.trim()] = rest.join(":").trim();
  }
  return fm;
}

async function getActiveProjects() {
  const dir = path.join(VAULT, "Will/Projects");
  let files;
  try { files = await fs.readdir(dir); } catch { return []; }
  const projects = [];
  for (const file of files) {
    if (!file.endsWith(".md")) continue;
    const slug = file.replace(/\.md$/, "");
    try {
      const content = await fs.readFile(path.join(dir, file), "utf8");
      const fm = parseFrontmatter(content);
      if (fm.status === "active") {
        const titleMatch = content.match(/^# (.+)$/m);
        const title = titleMatch ? titleMatch[1].split("—")[0].trim() : slug;
        projects.push({ title, path: `Will/Projects/${slug}` });
      }
    } catch { /* unreadable note */ }
  }
  return projects;
}

async function getRecentSessions(count = 5) {
  const dir = path.join(VAULT, "Memory/Sessions");
  let files;
  try { files = await fs.readdir(dir); } catch { return []; }
  return files
    .filter(file => file.endsWith(".md") && /^\d{4}-\d{2}-\d{2}/.test(file))
    .sort()
    .reverse()
    .slice(0, count)
    .map(file => `Memory/Sessions/${file.replace(/\.md$/, "")}`);
}

async function getOpenLoops(dateStr) {
  try {
    const content = await fs.readFile(path.join(VAULT, "Memory/Daily", `${dateStr}.md`), "utf8");
    return content.split("\n").filter(line => line.trim().startsWith("- [ ]"));
  } catch {
    return [];
  }
}

async function generate() {
  if (!VAULT) {
    console.error("Set OBSIDIAN_VAULT to your vault.");
    process.exit(2);
  }
  const today = todayInZone();
  const week = weekLabel(today);
  const [projects, sessions, openLoops] = await Promise.all([
    getActiveProjects(),
    getRecentSessions(5),
    getOpenLoops(today)
  ]);
  const projectLines = projects.length
    ? projects.map(item => `- [[${item.path}|${item.title}]]`).join("\n")
    : "*No active projects found in Will/Projects/.*";
  const sessionLines = sessions.length
    ? sessions.map(item => `- [[${item}]]`).join("\n")
    : "*No sessions yet.*";
  const loopLines = openLoops.length
    ? openLoops.join("\n")
    : "*No open loops in today's note — or the note is not written yet.*";
  const output = `---
type: moc
updated: ${today}
auto: true
tags: [moc, today, dashboard]
---

# Today — ${today}

← [[Bridges/Home|Home]]

---

## Active Projects

${projectLines}

---

## Today's Note

→ [[Memory/Daily/${today}]]

---

## Recent Sessions

${sessionLines}

---

## Open Loops

${loopLines}

---

## Navigation

**Week:** [[Memory/Weekly/${week}]]
**Agent Log:** [[Memory/Log/${today}]]
**Yesterday:** [[Memory/Daily/${previousDay(today)}]]

---

*Auto-generated by generate-today.mjs. Edit [[Memory/Daily/${today}]] for human notes.*
`;
  const outPath = path.join(VAULT, "Bridges/Today.md");
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, output, "utf8");
  console.log(`Bridges/Today.md updated for ${today}`);
}

generate().catch(err => {
  console.error(err);
  process.exit(1);
});
